repos:

- repo: https://github.com/asottile/pyupgrade
  rev: v3.3.2
  hooks:
  - id: pyupgrade
    args: [--py310-plus]

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-ast
  - id: trailing-whitespace
  - id: debug-statements
  - id: end-of-file-fixer

- repo: https://github.com/psf/black
  rev: 23.3.0
  hooks:
  - id: black

- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.16
  hooks:
  - id: mdformat
    additional_dependencies:
    - mdformat-gfm
    - mdformat-black
    args: [--wrap, '99']


- repo: https://github.com/python-poetry/poetry
  rev: '1.4.0'
  hooks:
    - id: poetry-check

- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.264'
  hooks:
    - id: ruff
      args: [--fix]

- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
      args: [--profile, black]
