name: CI

# Run on every push to master, every tag starting with 'v' and all pull requests
on:
  push:
    branches: [ master ]
    tags: [ v* ]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11"]
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          architecture: x64
      - run: poetry install --all-extras
      - run: poetry run pytest

  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: "3.10"
    - uses: pre-commit/action@v3.0.0

  publish:
    if: startsWith(github.event.ref, 'refs/tags/v')
    name: publish
    needs: [tests, pre-commit]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: pipx install poetry
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          architecture: x64
      - run: poetry build
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password_test }}
          repository_url: https://test.pypi.org/legacy/
      - uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.pypi_password }}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          body: |
            Changes:
            - ...
            - ...
          draft: true
          prerelease: false
